title: International Press journal JOC author support
description: TeX related material for the manuscript preparation for the
             International Press journal Journal of Combinatorics (JOC)
show_downloads: true
theme: jekyll-theme-tactile
